# Generated by Django 5.2.5 on 2025-08-08 01:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Proyecto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200, verbose_name='Título del proyecto')),
                ('descripcion', models.TextField(verbose_name='Descripción')),
                ('imagen', models.ImageField(upload_to='proyectos/', verbose_name='Imagen principal')),
                ('video_url', models.URLField(blank=True, null=True, verbose_name='Enlace a video')),
                ('fecha_inicio', models.DateField(verbose_name='Fecha de inicio')),
                ('fecha_fin', models.DateField(blank=True, null=True, verbose_name='Fecha de finalización')),
                ('estado', models.CharField(choices=[('EN_PROGRESO', 'En progreso'), ('COMPLETADO', 'Completado'), ('PAUSADO', 'Pausado'), ('PLANEADO', 'Planeado')], default='EN_PROGRESO', editable=False, max_length=20)),
                ('url_demo', models.URLField(blank=True, null=True, verbose_name='URL de demostración')),
                ('url_repositorio', models.URLField(blank=True, null=True, verbose_name='URL de repositorio')),
                ('tecnologias', models.CharField(blank=True, help_text='Separar con comas', max_length=200, null=True, verbose_name='Tecnologías utilizadas')),
            ],
            options={
                'verbose_name': 'Proyecto',
                'verbose_name_plural': 'Proyectos',
                'ordering': ['-fecha_inicio'],
            },
        ),
    ]
