# Generated by Django 5.2.5 on 2025-08-08 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyectos', '0002_proyecto_empresa'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contacto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('celular', models.CharField(max_length=15, verbose_name='Celular')),
                ('mensaje', models.TextField(verbose_name='Mensaje')),
                ('fecha_contacto', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de contacto')),
            ],
            options={
                'verbose_name': 'Contacto',
                'verbose_name_plural': 'Contactos',
                'ordering': ['-fecha_contacto'],
            },
        ),
    ]
