# Generated by Django 5.2.5 on 2025-08-14 23:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyectos', '0003_contacto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proyecto',
            name='imagen',
            field=models.URLField(blank=True, null=True, verbose_name='Imagen principal'),
        ),
    ]
